import * as vscode from 'vscode';

export function showYamlWizard(context: vscode.ExtensionContext) {
    const panel = vscode.window.createWebviewPanel(
        'yamlWizard',
        'NeuralForge Configuration Wizard',
        vscode.ViewColumn.One,
        {
            enableScripts: true
        }
    );

    panel.webview.html = getWebviewContent();

    panel.webview.onDidReceiveMessage(
        message => {
            switch (message.command) {
                case 'generate':
                    const yamlContent = generateYamlFromData(message.data);
                    vscode.workspace.openTextDocument({ content: yamlContent, language: 'yaml' })
                        .then(doc => vscode.window.showTextDocument(doc));
                    return;
            }
        },
        undefined,
        context.subscriptions
    );
}

function generateYamlFromData(data: any): string {
    const tuneStr = data.tune ? 'true' : 'false';
    const batchSize = data.batchSize || 16;
    
    return `model: "${data.model || 'yolov8n.pt'}"
type: "yolo"
train:
  task: "${data.task || 'detect'}"
  data: "${data.dataset || '/path/to/data'}"
  epochs: ${data.epochs || 100}
  batch: ${batchSize}
  imgsz: 640
sweeper:
  version: 2
  study_name: "${data.project}_${data.datasetName}"
  direction: "maximize"
  fitness: "metrics/mAP50-95(B)"
  algorithm: "optuna"
  tune: ${tuneStr}
  n_trials: ${data.nTrials || 3}
  search_space:
    model: ["choice", "${data.model || 'yolov8n.pt'}"]
    train:
      imgsz: ["choice", 640]
      lr0: ["float", ${data.lrMin || 0.001}, ${data.lrMax || 0.01}]
      batch: ["choice", ${batchSize}]
metadata:
  content: "YOLO training dataset generated by NeuralForge VSCode Wizard"
  author: "User"
  documentation: "Auto-generated"
`;
}

function getWebviewContent() {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Configuration Wizard</title>
    <style>
        body { 
            font-family: 'Inter', sans-serif; 
            padding: 20px; 
            background-color: var(--vscode-editor-background);
            color: var(--vscode-editor-foreground);
            max-width: 600px;
            margin: 0 auto;
        }
        h2 {
            border-bottom: 2px solid var(--vscode-button-background);
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .form-group { 
            margin-bottom: 18px; 
            transition: all 0.3s ease;
        }
        .form-group:hover {
            transform: translateX(5px);
        }
        label { 
            display: block; 
            margin-bottom: 6px; 
            font-weight: 600;
            font-size: 13px;
        }
        input, select { 
            width: 100%; 
            padding: 10px; 
            box-sizing: border-box; 
            background: var(--vscode-input-background); 
            color: var(--vscode-input-foreground); 
            border: 1px solid var(--vscode-input-border); 
            border-radius: 4px;
            transition: border-color 0.3s ease;
        }
        input:focus, select:focus {
            outline: none;
            border-color: var(--vscode-focusBorder);
        }
        .row {
            display: flex;
            gap: 15px;
        }
        .col { flex: 1; }
        .checkbox-group {
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .checkbox-group input {
            width: auto;
        }
        button { 
            width: 100%;
            padding: 12px 15px; 
            background: var(--vscode-button-background); 
            color: var(--vscode-button-foreground); 
            border: none; 
            border-radius: 4px;
            font-size: 14px;
            font-weight: bold;
            cursor: pointer; 
            transition: background 0.3s ease, transform 0.1s ease;
            margin-top: 20px;
        }
        button:hover { 
            background: var(--vscode-button-hoverBackground); 
        }
        button:active {
            transform: scale(0.98);
        }
        .error {
            color: var(--vscode-errorForeground);
            font-size: 12px;
            margin-top: 5px;
            display: none;
        }
    </style>
</head>
<body>
    <h2>NeuralForge Training Wizard</h2>
    
    <div class="row">
        <div class="form-group col">
            <label>Project Name <span style="color:red">*</span></label>
            <input type="text" id="project" placeholder="e.g. arepo" required>
            <div id="projectError" class="error">Required field</div>
        </div>
        <div class="form-group col">
            <label>Dataset Name <span style="color:red">*</span></label>
            <input type="text" id="datasetName" placeholder="e.g. cicatrices" required>
            <div id="datasetNameError" class="error">Required field</div>
        </div>
    </div>

    <div class="form-group">
        <label>Dataset Path (on Server) <span style="color:red">*</span></label>
        <input type="text" id="dataset" placeholder="/data/datasets/arepo_cicatrices.yaml" required>
        <div id="datasetError" class="error">Must be a valid .yaml path</div>
    </div>

    <div class="row">
        <div class="form-group col">
            <label>Task</label>
            <select id="task">
                <option value="detect">Detection</option>
                <option value="segment">Segmentation</option>
                <option value="classify">Classification</option>
            </select>
        </div>
        <div class="form-group col">
            <label>Model</label>
            <select id="model">
                <option value="yolov8n.pt">YOLOv8 Nano</option>
                <option value="yolov8s.pt">YOLOv8 Small</option>
                <option value="yolov8m.pt">YOLOv8 Medium</option>
                <option value="yolov8l.pt">YOLOv8 Large</option>
                <option value="yolov8n-seg.pt">YOLOv8 Nano (Seg)</option>
            </select>
        </div>
    </div>

    <div class="row">
        <div class="form-group col">
            <label>Epochs</label>
            <input type="number" id="epochs" value="100" min="1">
        </div>
        <div class="form-group col">
            <label>Batch Size</label>
            <select id="batchSize">
                <option value="8">8</option>
                <option value="16" selected>16</option>
                <option value="32">32</option>
                <option value="64">64</option>
            </select>
        </div>
    </div>

    <h3 style="margin-top:20px; border-bottom:1px solid #ccc; padding-bottom:5px;">Hyperparameter Tuning (Optuna)</h3>
    <div class="form-group checkbox-group">
        <input type="checkbox" id="tune">
        <label style="margin:0;">Enable Auto-Tuning (Sweeper)</label>
    </div>

    <div class="row">
        <div class="form-group col">
            <label>Number of Trials</label>
            <input type="number" id="nTrials" value="3" min="1">
        </div>
        <div class="form-group col">
            <label>LR Min</label>
            <input type="number" id="lrMin" value="0.001" step="0.0001">
        </div>
        <div class="form-group col">
            <label>LR Max</label>
            <input type="number" id="lrMax" value="0.01" step="0.001">
        </div>
    </div>

    <button onclick="validateAndGenerate()">Generate YAML</button>

    <script>
        const vscode = acquireVsCodeApi();

        function validateAndGenerate() {
            let isValid = true;
            
            const project = document.getElementById('project').value.trim();
            const datasetName = document.getElementById('datasetName').value.trim();
            const dataset = document.getElementById('dataset').value.trim();
            
            // Validations
            if (!project) {
                document.getElementById('projectError').style.display = 'block';
                isValid = false;
            } else {
                document.getElementById('projectError').style.display = 'none';
            }

            if (!datasetName) {
                document.getElementById('datasetNameError').style.display = 'block';
                isValid = false;
            } else {
                document.getElementById('datasetNameError').style.display = 'none';
            }

            if (!dataset || !dataset.endsWith('.yaml')) {
                document.getElementById('datasetError').style.display = 'block';
                isValid = false;
            } else {
                document.getElementById('datasetError').style.display = 'none';
            }

            if (isValid) {
                const data = {
                    project: project,
                    datasetName: datasetName,
                    dataset: dataset,
                    task: document.getElementById('task').value,
                    model: document.getElementById('model').value,
                    epochs: parseInt(document.getElementById('epochs').value, 10),
                    batchSize: parseInt(document.getElementById('batchSize').value, 10),
                    tune: document.getElementById('tune').checked,
                    nTrials: parseInt(document.getElementById('nTrials').value, 10),
                    lrMin: parseFloat(document.getElementById('lrMin').value),
                    lrMax: parseFloat(document.getElementById('lrMax').value)
                };
                
                vscode.postMessage({
                    command: 'generate',
                    data: data
                });
            }
        }
    </script>
</body>
</html>`;
}

