import * as vscode from 'vscode';

export function showYamlWizard(context: vscode.ExtensionContext) {
    const panel = vscode.window.createWebviewPanel(
        'yamlWizard',
        'NeuralForge Configuration Wizard',
        vscode.ViewColumn.One,
        {
            enableScripts: true
        }
    );

    panel.webview.html = getWebviewContent();

    panel.webview.onDidReceiveMessage(
        message => {
            switch (message.command) {
                case 'generate':
                    const yamlContent = generateYamlFromData(message.data);
                    vscode.workspace.openTextDocument({ content: yamlContent, language: 'yaml' })
                        .then(doc => vscode.window.showTextDocument(doc));
                    return;
            }
        },
        undefined,
        context.subscriptions
    );
}

function generateYamlFromData(data: any): string {
    return `model: "${data.model || 'yolov8n.pt'}"
type: "yolo"
train:
  task: "${data.task || 'detect'}"
  data: "${data.dataset || '/path/to/data'}"
  epochs: ${data.epochs || 100}
  imgsz: 640
sweeper:
  version: 2
  study_name: "${data.project}_${data.datasetName}"
  direction: "maximize"
  fitness: "metrics/mAP50-95(B)"
  algorithm: "optuna"
  tune: false
  n_trials: 3
  search_space:
    model: ["choice", "${data.model || 'yolov8n.pt'}"]
    train:
      imgsz: ["choice", 640]
metadata:
  content: "YOLO training dataset generated by NeuralForge VSCode Wizard"
  author: "User"
  documentation: "Auto-generated"
`;
}

function getWebviewContent() {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Configuration Wizard</title>
    <style>
        body { font-family: sans-serif; padding: 20px; }
        .form-group { margin-bottom: 15px; }
        label { display: block; margin-bottom: 5px; }
        input, select { width: 100%; padding: 8px; box-sizing: border-box; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border); }
        button { padding: 10px 15px; background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: none; cursor: pointer; }
        button:hover { background: var(--vscode-button-hoverBackground); }
    </style>
</head>
<body>
    <h2>NeuralForge Training Wizard</h2>
    <div class="form-group">
        <label>Project Name</label>
        <input type="text" id="project" placeholder="e.g. arepo">
    </div>
    <div class="form-group">
        <label>Dataset Name</label>
        <input type="text" id="datasetName" placeholder="e.g. cicatrices">
    </div>
    <div class="form-group">
        <label>Dataset Path (on Server)</label>
        <input type="text" id="dataset" placeholder="/data/datasets/arepo_cicatrices.yaml">
    </div>
    <div class="form-group">
        <label>Task</label>
        <select id="task">
            <option value="detect">Detection</option>
            <option value="segment">Segmentation</option>
            <option value="classify">Classification</option>
        </select>
    </div>
    <div class="form-group">
        <label>Model</label>
        <select id="model">
            <option value="yolov8n.pt">YOLOv8 Nano</option>
            <option value="yolov8s.pt">YOLOv8 Small</option>
            <option value="yolov8m.pt">YOLOv8 Medium</option>
            <option value="yolov8n-seg.pt">YOLOv8 Nano (Seg)</option>
        </select>
    </div>
    <div class="form-group">
        <label>Epochs</label>
        <input type="number" id="epochs" value="100">
    </div>
    <button onclick="generate()">Generate YAML</button>

    <script>
        const vscode = acquireVsCodeApi();
        function generate() {
            const data = {
                project: document.getElementById('project').value || 'project',
                datasetName: document.getElementById('datasetName').value || 'dataset',
                dataset: document.getElementById('dataset').value,
                task: document.getElementById('task').value,
                model: document.getElementById('model').value,
                epochs: document.getElementById('epochs').value
            };
            vscode.postMessage({
                command: 'generate',
                data: data
            });
        }
    </script>
</body>
</html>`;
}
